# Generated by Django 4.2 on 2023-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_file_file_type_alter_file_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'audio'), (3, 'pdf'), (2, 'video')], default=2, verbose_name='file type'),
        ),
    ]
